[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "jsonpath-ng"
version = "1.9.1"
description="A final implementation of JSONPath for Python that aims to be standard compliant, including arithmetic and binary comparison operators and providing clear AST for metaprogramming."
authors = [
    {name = "Tomas Aparicio", email = "tomas@aparicio.me"},
]
license = "Apache-2.0"
readme = "README.rst"
requires-python = ">= 3.11"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]

[project.urls]
Source = "https://github.com/jsonpath-ng/jsonpath-ng"

[project.scripts]
jsonpath_ng = "jsonpath_ng.bin.jsonpath:entry_point"

[dependency-groups]
dev = [
    "flake8",
    "hypothesis",
    "pytest",
    "pytest-randomly",
    "scriv",
    "tox",
]


# mypy
# ----

[tool.mypy]
packages = "jsonpath_ng"
# strict = true
sqlite_cache = true

[[tool.mypy.overrides]]
ignore_errors = true
module = [
    "jsonpath_ng._ply.*",
]


# pytest
# ------

[tool.pytest.ini_options]
filterwarnings = [
    # Escalate warnings to errors.
    "error",

    # The ply package doesn't close its debug log file. Ignore this warning.
    "ignore::ResourceWarning",
]


# codespell
# ---------

[tool.codespell]
skip = '.git,.gitignore,.gitattributes,*.pdf,*.svg,*.css,*.min.*,_ply,./.venv'
check-hidden = true
ignore-words-list = 'nd'


# scriv
# -----

[tool.scriv]
version = "literal: pyproject.toml: project.version"
categories = [
    "Python support",
    "Added",
    "Fixed",
    "Removed",
    "Changed",
    "Deprecated",
    "Security",
    "Documentation",
    "Project administration",
]
entry_title_template = "{{ version }} - {{ date.strftime('%Y-%m-%d') }}"
format = "rst"
fragment_directory = "changelog.d"
insert_marker = "scriv-insert-here"
main_branches = [
    "main",
    "releases",
]
new_fragment_template = "file: fragment-template.rst.txt"
