[tox]
min_version = 4.3.5

envlist =
    build{, -minimum}
    coverage-erase
    py{3.15, 3.14, 3.13, 3.12, 3.11}
    mypy-py{3.15, 3.14, 3.13, 3.12, 3.11}
    coverage-report

skip_missing_interpreters = True
isolated_build = True


[testenv]
package = wheel
wheel_build_env = build_wheel

depends =
    py{3.15, 3.14, 3.13, 3.12, 3.11}: coverage-erase
dependency_groups =
    test
commands =
    coverage run -m pytest


[testenv:build{, -minimum}]
description =
    Test building the project
    minimum: (minimum requirements)
base_python =
    minimum: py3.10
skip_install = true
recreate = true
deps =
    build
    twine
    minimum: setuptools==77.0.3
    !minimum: setuptools
commands =
    python --version
    python -m build --outdir {envdir}/dist/ --no-isolation
    twine check --strict {envdir}/dist/*


[testenv:coverage-erase]
no_package = true
skip_install = true
dependency_groups =
    coverage
commands =
    coverage erase


[testenv:coverage-report]
depends =
    py{3.15, 3.14, 3.13, 3.12, 3.11}
no_package = true
skip_install = true
dependency_groups =
    coverage
commands_pre =
    - coverage combine
commands =
    coverage report
commands_post =
    coverage html --fail-under=0


[testenv:mypy-py{3.15, 3.14, 3.13, 3.12, 3.11}]
deps =
    mypy
commands =
    mypy {posargs}


[testenv:benchmark]
dependency_groups =
    test
commands =
    pytest --codspeed --verbose --randomly-dont-reorganize --randomly-dont-reset-seed
